Added Delphi and C++Builder
langserver/langserver.github.io pull request #223
Opened 2020-09-22 13:11 UTC by vintagedave

Delphi and C++Builder are sibling products which use same IDE, RAD Studio, and both support LSP. C++Builder uses a modified version of cquery, so only the IDE has been added. Delphi has its own server, so both the IDE and server are listed here. Both products are closed source: links to go product or documentation pages, not a source repo.

They have been added in alphabetical order in each table.

2020-09-22 22:44 UTC, keegancsmith requested changes
Hey you included delphi twice here. Mind updating?

2020-09-22 22:44 UTC, keegancsmith commented
whoops, didn't read your description and PR close enough :) accepting.

2020-09-22 22:44 UTC, keegancsmith approved these changes

2020-09-22 22:44 UTC, merged

2020-09-23 10:48 UTC, vintagedave commented
@keegancsmith Thanks!